# TCL File Generated by Component Editor 12.1
# Sun Apr 11 17:05:55 CST 2021
# DO NOT MODIFY


# 
# avalon_dvp_wch "avalon_dvp_wch" v1.0
# bxq 2021.04.11.17:05:55
# avalon_dvp_wch
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module avalon_dvp_wch
# 
set_module_property DESCRIPTION avalon_dvp_wch
set_module_property NAME avalon_dvp_wch
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP bxq
set_module_property AUTHOR bxq
set_module_property DISPLAY_NAME avalon_dvp_wch
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_dvp_wch
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file avalon_dvp_wch.v VERILOG PATH ./rtl/avalon_dvp_wch.v
add_fileset_file burst_write_master.v VERILOG PATH ./rtl/burst_write_master.v
add_fileset_file write_master.v VERILOG PATH ./rtl/write_master.v


# 
# parameters
# 
add_parameter AM_DATA_WIDTH INTEGER 16
set_parameter_property AM_DATA_WIDTH DEFAULT_VALUE 16
set_parameter_property AM_DATA_WIDTH DISPLAY_NAME AM_DATA_WIDTH
set_parameter_property AM_DATA_WIDTH TYPE INTEGER
set_parameter_property AM_DATA_WIDTH UNITS None
set_parameter_property AM_DATA_WIDTH HDL_PARAMETER true
add_parameter AM_MAX_BURST_COUNT INTEGER 4
set_parameter_property AM_MAX_BURST_COUNT DEFAULT_VALUE 4
set_parameter_property AM_MAX_BURST_COUNT DISPLAY_NAME AM_MAX_BURST_COUNT
set_parameter_property AM_MAX_BURST_COUNT TYPE INTEGER
set_parameter_property AM_MAX_BURST_COUNT UNITS None
set_parameter_property AM_MAX_BURST_COUNT HDL_PARAMETER true
add_parameter AM_BURST_COUNT_WIDTH INTEGER 3
set_parameter_property AM_BURST_COUNT_WIDTH DEFAULT_VALUE 3
set_parameter_property AM_BURST_COUNT_WIDTH DISPLAY_NAME AM_BURST_COUNT_WIDTH
set_parameter_property AM_BURST_COUNT_WIDTH TYPE INTEGER
set_parameter_property AM_BURST_COUNT_WIDTH UNITS None
set_parameter_property AM_BURST_COUNT_WIDTH HDL_PARAMETER true
add_parameter AM_ADDRESS_WIDTH INTEGER 32
set_parameter_property AM_ADDRESS_WIDTH DEFAULT_VALUE 32
set_parameter_property AM_ADDRESS_WIDTH DISPLAY_NAME AM_ADDRESS_WIDTH
set_parameter_property AM_ADDRESS_WIDTH TYPE INTEGER
set_parameter_property AM_ADDRESS_WIDTH UNITS None
set_parameter_property AM_ADDRESS_WIDTH HDL_PARAMETER true
add_parameter AM_FIFO_DEPTH INTEGER 32
set_parameter_property AM_FIFO_DEPTH DEFAULT_VALUE 32
set_parameter_property AM_FIFO_DEPTH DISPLAY_NAME AM_FIFO_DEPTH
set_parameter_property AM_FIFO_DEPTH TYPE INTEGER
set_parameter_property AM_FIFO_DEPTH UNITS None
set_parameter_property AM_FIFO_DEPTH HDL_PARAMETER true
add_parameter AM_FIFO_DEPTH_LOG2 INTEGER 5
set_parameter_property AM_FIFO_DEPTH_LOG2 DEFAULT_VALUE 5
set_parameter_property AM_FIFO_DEPTH_LOG2 DISPLAY_NAME AM_FIFO_DEPTH_LOG2
set_parameter_property AM_FIFO_DEPTH_LOG2 TYPE INTEGER
set_parameter_property AM_FIFO_DEPTH_LOG2 UNITS None
set_parameter_property AM_FIFO_DEPTH_LOG2 HDL_PARAMETER true
add_parameter AM_MEMORY_BASED_FIFO INTEGER 1
set_parameter_property AM_MEMORY_BASED_FIFO DEFAULT_VALUE 1
set_parameter_property AM_MEMORY_BASED_FIFO DISPLAY_NAME AM_MEMORY_BASED_FIFO
set_parameter_property AM_MEMORY_BASED_FIFO TYPE INTEGER
set_parameter_property AM_MEMORY_BASED_FIFO UNITS None
set_parameter_property AM_MEMORY_BASED_FIFO HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset reset reset Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true

add_interface_port avalon_master am_write write Output 1
add_interface_port avalon_master am_writedata writedata Output AM_DATA_WIDTH
add_interface_port avalon_master am_address address Output AM_ADDRESS_WIDTH
add_interface_port avalon_master am_burstcount burstcount Output AM_BURST_COUNT_WIDTH
add_interface_port avalon_master am_waitrequest waitrequest Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true

add_interface_port conduit_end pclk export Input 1
add_interface_port conduit_end href export Input 1
add_interface_port conduit_end vsync export Input 1
add_interface_port conduit_end raw export Input AM_DATA_WIDTH


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave addressAlignment NATIVE
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true

add_interface_port avalon_slave as_read read Input 1
add_interface_port avalon_slave as_readdata readdata Output 32
add_interface_port avalon_slave as_write write Input 1
add_interface_port avalon_slave as_writedata writedata Input 32
add_interface_port avalon_slave as_address address Input 2
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0

