# TCL File Generated by Component Editor 12.1
# Sun Apr 18 15:33:06 CST 2021
# DO NOT MODIFY


# 
# avalon_dvp_vi "avalon_dvp_vi" v1.0
# bxq 2021.04.18.15:33:06
# avalon_dvp_vi
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module avalon_dvp_vi
# 
set_module_property DESCRIPTION avalon_dvp_vi
set_module_property NAME avalon_dvp_vi
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP bxq
set_module_property AUTHOR bxq
set_module_property DISPLAY_NAME avalon_dvp_vi
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_dvp_vi
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file avalon_dvp_vi.v VERILOG PATH ./rtl/avalon_dvp_vi.v
add_fileset_file dvp_raw_timing_colorbar.v VERILOG PATH ./rtl/dvp_raw_timing_colorbar.v


# 
# parameters
# 
add_parameter BITS INTEGER 8
set_parameter_property BITS DEFAULT_VALUE 8
set_parameter_property BITS DISPLAY_NAME BITS
set_parameter_property BITS TYPE INTEGER
set_parameter_property BITS UNITS None
set_parameter_property BITS HDL_PARAMETER true
add_parameter COLORBAR_H_FRONT STD_LOGIC_VECTOR 200
set_parameter_property COLORBAR_H_FRONT DEFAULT_VALUE 200
set_parameter_property COLORBAR_H_FRONT DISPLAY_NAME COLORBAR_H_FRONT
set_parameter_property COLORBAR_H_FRONT TYPE STD_LOGIC_VECTOR
set_parameter_property COLORBAR_H_FRONT UNITS None
set_parameter_property COLORBAR_H_FRONT ALLOWED_RANGES 0:262143
set_parameter_property COLORBAR_H_FRONT HDL_PARAMETER true
add_parameter COLORBAR_H_PULSE STD_LOGIC_VECTOR 536
set_parameter_property COLORBAR_H_PULSE DEFAULT_VALUE 536
set_parameter_property COLORBAR_H_PULSE DISPLAY_NAME COLORBAR_H_PULSE
set_parameter_property COLORBAR_H_PULSE TYPE STD_LOGIC_VECTOR
set_parameter_property COLORBAR_H_PULSE UNITS None
set_parameter_property COLORBAR_H_PULSE ALLOWED_RANGES 0:262143
set_parameter_property COLORBAR_H_PULSE HDL_PARAMETER true
add_parameter COLORBAR_H_BACK STD_LOGIC_VECTOR 200
set_parameter_property COLORBAR_H_BACK DEFAULT_VALUE 200
set_parameter_property COLORBAR_H_BACK DISPLAY_NAME COLORBAR_H_BACK
set_parameter_property COLORBAR_H_BACK TYPE STD_LOGIC_VECTOR
set_parameter_property COLORBAR_H_BACK UNITS None
set_parameter_property COLORBAR_H_BACK ALLOWED_RANGES 0:262143
set_parameter_property COLORBAR_H_BACK HDL_PARAMETER true
add_parameter COLORBAR_H_DISP STD_LOGIC_VECTOR 960
set_parameter_property COLORBAR_H_DISP DEFAULT_VALUE 960
set_parameter_property COLORBAR_H_DISP DISPLAY_NAME COLORBAR_H_DISP
set_parameter_property COLORBAR_H_DISP TYPE STD_LOGIC_VECTOR
set_parameter_property COLORBAR_H_DISP UNITS None
set_parameter_property COLORBAR_H_DISP ALLOWED_RANGES 0:262143
set_parameter_property COLORBAR_H_DISP HDL_PARAMETER true
add_parameter COLORBAR_V_FRONT STD_LOGIC_VECTOR 100
set_parameter_property COLORBAR_V_FRONT DEFAULT_VALUE 100
set_parameter_property COLORBAR_V_FRONT DISPLAY_NAME COLORBAR_V_FRONT
set_parameter_property COLORBAR_V_FRONT TYPE STD_LOGIC_VECTOR
set_parameter_property COLORBAR_V_FRONT UNITS None
set_parameter_property COLORBAR_V_FRONT ALLOWED_RANGES 0:262143
set_parameter_property COLORBAR_V_FRONT HDL_PARAMETER true
add_parameter COLORBAR_V_PULSE STD_LOGIC_VECTOR 240
set_parameter_property COLORBAR_V_PULSE DEFAULT_VALUE 240
set_parameter_property COLORBAR_V_PULSE DISPLAY_NAME COLORBAR_V_PULSE
set_parameter_property COLORBAR_V_PULSE TYPE STD_LOGIC_VECTOR
set_parameter_property COLORBAR_V_PULSE UNITS None
set_parameter_property COLORBAR_V_PULSE ALLOWED_RANGES 0:262143
set_parameter_property COLORBAR_V_PULSE HDL_PARAMETER true
add_parameter COLORBAR_V_BACK STD_LOGIC_VECTOR 100
set_parameter_property COLORBAR_V_BACK DEFAULT_VALUE 100
set_parameter_property COLORBAR_V_BACK DISPLAY_NAME COLORBAR_V_BACK
set_parameter_property COLORBAR_V_BACK TYPE STD_LOGIC_VECTOR
set_parameter_property COLORBAR_V_BACK UNITS None
set_parameter_property COLORBAR_V_BACK ALLOWED_RANGES 0:262143
set_parameter_property COLORBAR_V_BACK HDL_PARAMETER true
add_parameter COLORBAR_V_DISP STD_LOGIC_VECTOR 544
set_parameter_property COLORBAR_V_DISP DEFAULT_VALUE 544
set_parameter_property COLORBAR_V_DISP DISPLAY_NAME COLORBAR_V_DISP
set_parameter_property COLORBAR_V_DISP TYPE STD_LOGIC_VECTOR
set_parameter_property COLORBAR_V_DISP UNITS None
set_parameter_property COLORBAR_V_DISP ALLOWED_RANGES 0:262143
set_parameter_property COLORBAR_V_DISP HDL_PARAMETER true
add_parameter COLORBAR_BAYER INTEGER 0
set_parameter_property COLORBAR_BAYER DEFAULT_VALUE 0
set_parameter_property COLORBAR_BAYER DISPLAY_NAME COLORBAR_BAYER
set_parameter_property COLORBAR_BAYER TYPE INTEGER
set_parameter_property COLORBAR_BAYER UNITS None
set_parameter_property COLORBAR_BAYER HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset reset reset Input 1


# 
# connection point as
# 
add_interface as avalon end
set_interface_property as addressUnits WORDS
set_interface_property as addressAlignment NATIVE
set_interface_property as associatedClock clock
set_interface_property as associatedReset reset
set_interface_property as bitsPerSymbol 8
set_interface_property as burstOnBurstBoundariesOnly false
set_interface_property as burstcountUnits WORDS
set_interface_property as explicitAddressSpan 0
set_interface_property as holdTime 0
set_interface_property as linewrapBursts false
set_interface_property as maximumPendingReadTransactions 0
set_interface_property as readLatency 0
set_interface_property as readWaitTime 1
set_interface_property as setupTime 0
set_interface_property as timingUnits Cycles
set_interface_property as writeWaitTime 0
set_interface_property as ENABLED true

add_interface_port as as_address address Input 6
add_interface_port as as_read read Input 1
add_interface_port as as_readdata readdata Output 32
add_interface_port as as_write write Input 1
add_interface_port as as_writedata writedata Input 32
set_interface_assignment as embeddedsw.configuration.isFlash 0
set_interface_assignment as embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment as embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment as embeddedsw.configuration.isPrintableDevice 0


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint as
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset
set_interface_property interrupt_sender ENABLED true

add_interface_port interrupt_sender as_irq irq Output 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true

add_interface_port conduit_end cmos_xclk export Input 1
add_interface_port conduit_end cmos_pclk export Input 1
add_interface_port conduit_end cmos_href export Input 1
add_interface_port conduit_end cmos_vsync export Input 1
add_interface_port conduit_end cmos_db export Input BITS
add_interface_port conduit_end out_pclk export Output 1
add_interface_port conduit_end out_href export Output 1
add_interface_port conduit_end out_vsync export Output 1
add_interface_port conduit_end out_raw export Output BITS

